// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// hub75 //
// ----- //

#define hub75_wrap_target 0
#define hub75_wrap 2
#define hub75_pio_version 0

static const uint16_t hub75_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0
    0x6306, //  1: out    pins, 6         side 0 [3]
    0xb342, //  2: nop                    side 1 [3]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program hub75_program = {
    .instructions = hub75_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = hub75_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config hub75_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hub75_wrap_target, offset + hub75_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

